language: java

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

sudo: false
script: mvn verify javadoc:javadoc -Ptravis

#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: target/site/apidocs
#  on:
#    branch: master

notifications:
  email:
    on_sucess: never
    on_failure: always
