language: java
sudo: false
script: mvn test javadoc:javadoc

#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: target/site/apidocs
#  on:
#    branch: master

after_success:
  - mvn clean cobertura:cobertura coveralls:report -DrepoToken=vOqwyAtdaMwCCFpe5dtjl0S6AcDIsfPre

notifications:
  email:
    on_sucess: never
    on_failure: always