language: java
sudo: false
script: mvn test javadoc:javadoc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/site/apidocs
  github_token: 473faff4af91b23a95c4e58fb1682322b7a96ed3
  on:
    branch: master